import { StyleSheet } from 'react-native';
import { AppColors } from '../constants/appColors';
import { Theme } from './theme';

// ================= 1. HOME SCREEN STYLES =================
export const homeStyles = StyleSheet.create({
  headerBanner: {
    paddingHorizontal: Theme.spacing.xxl,
    paddingBottom: Theme.spacing.xxxl,
  },
  greetingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Theme.spacing.lg,
  },
  greetingSub: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: Theme.typography.sizes.sm,
    fontWeight: Theme.typography.weights.medium,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  greetingName: {
    color: '#FFFFFF',
    fontSize: Theme.typography.sizes.xl,
    fontWeight: Theme.typography.weights.black,
    marginTop: 2,
  },
  nextClassCard: {
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: Theme.radii.lg,
    padding: Theme.spacing.lg,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  nextClassTag: {
    backgroundColor: AppColors.accent,
    borderRadius: Theme.radii.pill,
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: 2,
  },
  nextClassTagText: {
    color: '#FFFFFF',
    fontSize: Theme.typography.sizes.xs,
    fontWeight: Theme.typography.weights.bold,
  },
  nextClassTitle: {
    color: '#FFFFFF',
    fontWeight: Theme.typography.weights.black,
    fontSize: Theme.typography.sizes.lg,
    marginBottom: 6,
  },
  nextClassMetaText: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: Theme.typography.sizes.sm,
    marginLeft: 4,
  },
  quickActionGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  quickActionItem: {
    flex: 1,
    backgroundColor: AppColors.cardBg,
    borderRadius: Theme.radii.lg,
    padding: Theme.spacing.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: AppColors.border,
    ...Theme.shadows.card,
  },
  quickActionIcon: {
    width: 40,
    height: 40,
    borderRadius: Theme.radii.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Theme.spacing.sm,
  },
  quickActionLabel: {
    fontSize: Theme.typography.sizes.xs,
    fontWeight: Theme.typography.weights.bold,
    color: AppColors.textForeground,
    textAlign: 'center',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  statsItem: {
    width: '47%',
    backgroundColor: AppColors.cardBg,
    borderRadius: Theme.radii.lg,
    padding: Theme.spacing.lg,
    borderWidth: 1,
    borderColor: AppColors.border,
    ...Theme.shadows.card,
  },
  statsValue: {
    fontSize: Theme.typography.sizes.xl,
    fontWeight: Theme.typography.weights.black,
    color: AppColors.textForeground,
  },
  statsLabel: {
    fontSize: Theme.typography.sizes.xs,
    fontWeight: Theme.typography.weights.bold,
    color: AppColors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: 2,
  },
  statsSub: {
    fontSize: Theme.typography.sizes.xs,
    color: AppColors.textMuted,
  },
  eventCard: {
    borderRadius: Theme.radii.lg,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: AppColors.border,
    marginBottom: 10,
  },
  eventImage: {
    width: '100%',
    height: 128,
  },
  eventOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    top: 0,
    justifyContent: 'flex-end',
    padding: Theme.spacing.lg,
  },
});

// ================= 2. SCHEDULE SCREEN STYLES =================
export const scheduleStyles = StyleSheet.create({
  dayTabsTrack: {
    flexDirection: 'row',
    gap: 8,
  },
  dayTab: {
    flex: 1,
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radii.md,
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  dayTabActive: {
    backgroundColor: '#FFFFFF',
  },
  dayTabText: {
    fontSize: Theme.typography.sizes.sm,
    fontWeight: Theme.typography.weights.black,
    color: 'rgba(255,255,255,0.7)',
  },
  dayTabTextActive: {
    color: AppColors.primary,
  },
  statusBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: 2,
    borderRadius: Theme.radii.pill,
    borderWidth: 1,
    marginBottom: Theme.spacing.sm,
  },
  statusBadgeText: {
    fontSize: Theme.typography.sizes.xs,
    fontWeight: Theme.typography.weights.bold,
  },
  courseTitle: {
    fontSize: Theme.typography.sizes.md,
    fontWeight: Theme.typography.weights.black,
    color: AppColors.textForeground,
    marginBottom: 2,
  },
  courseCode: {
    fontSize: Theme.typography.sizes.sm,
    fontWeight: Theme.typography.weights.medium,
    color: AppColors.textMuted,
    marginBottom: Theme.spacing.md,
  },
  changedNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: Theme.spacing.md,
    backgroundColor: '#FFFBEB',
    borderRadius: Theme.radii.md,
    padding: 10,
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  changedNoticeText: {
    fontSize: Theme.typography.sizes.xs,
    color: '#92400E',
    fontWeight: Theme.typography.weights.medium,
    marginLeft: 8,
  },
  lecturerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: Theme.spacing.md,
  },
  lecturerIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(19,47,115,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
});

// ================= 3. GRADES SCREEN STYLES =================
export const gradesStyles = StyleSheet.create({
  studentCard: {
    backgroundColor: AppColors.cardBg,
    padding: Theme.spacing.xl,
    borderRadius: Theme.radii.xl,
    borderLeftWidth: 5,
    borderLeftColor: AppColors.primary,
    ...Theme.shadows.card,
  },
  studentIconBox: {
    width: 44,
    height: 44,
    borderRadius: Theme.radii.lg,
    backgroundColor: '#EEF2FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  courseCard: {
    backgroundColor: AppColors.cardBg,
    borderRadius: Theme.radii.lg,
    padding: Theme.spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: AppColors.border,
    ...Theme.shadows.card,
  },
  tableCard: {
    backgroundColor: AppColors.cardBg,
    padding: Theme.spacing.md,
    borderRadius: Theme.radii.lg,
    borderWidth: 1,
    borderColor: AppColors.border,
    ...Theme.shadows.card,
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: Theme.spacing.md,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 0.5,
    borderBottomColor: AppColors.border,
  },
  tableHeaderRow: {
    backgroundColor: '#F8FAFC',
    borderRadius: Theme.radii.sm,
    borderBottomWidth: 0,
  },
  letterGradeBox: {
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 4,
    borderRadius: Theme.radii.sm,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: 50,
  },
});

// ================= 4. MAP SCREEN STYLES =================
export const mapStyles = StyleSheet.create({
  mapCanvas: {
    marginHorizontal: Theme.spacing.lg,
    borderRadius: Theme.radii.lg,
    overflow: 'hidden',
    height: 280,
    backgroundColor: '#E8EDF5',
    borderWidth: 1,
    borderColor: AppColors.border,
    position: 'relative',
  },
  pinContainer: {
    position: 'absolute',
    transform: [{ translateX: -16 }, { translateY: -16 }],
  },
  pinBadge: {
    width: 32,
    height: 32,
    borderRadius: Theme.radii.md,
    alignItems: 'center',
    justifyContent: 'center',
    ...Theme.shadows.card,
  },
  pinTooltip: {
    position: 'absolute',
    bottom: 36,
    left: '50%',
    transform: [{ translateX: -60 }],
    backgroundColor: '#FFFFFF',
    borderRadius: Theme.radii.md,
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: AppColors.border,
    width: 120,
    ...Theme.shadows.elevated,
  },
  userPositionDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: AppColors.info,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    ...Theme.shadows.elevated,
  },
  compassBtn: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: AppColors.border,
    ...Theme.shadows.card,
  },
});

// ================= 5. FEEDBACK SCREEN STYLES =================
export const feedbackStyles = StyleSheet.create({
  categoryCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderRadius: Theme.radii.md,
    backgroundColor: AppColors.cardBg,
    borderWidth: 1.5,
    borderColor: AppColors.border,
    marginBottom: Theme.spacing.sm,
  },
  categoryCardSelected: {
    borderColor: AppColors.accent,
    backgroundColor: '#FAF5FF',
  },
  categoryIconBox: {
    width: 36,
    height: 36,
    borderRadius: Theme.radii.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Theme.spacing.md,
  },
  categoryLabel: {
    flex: 1,
    fontSize: Theme.typography.sizes.md,
    fontWeight: Theme.typography.weights.medium,
    color: AppColors.textForeground,
  },
  categoryLabelSelected: {
    fontWeight: Theme.typography.weights.extraBold,
    color: AppColors.primary,
  },
  starContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: Theme.spacing.xs,
  },
  starBtn: {
    padding: Theme.spacing.sm,
  },
  ratingText: {
    textAlign: 'center',
    fontSize: Theme.typography.sizes.sm,
    fontWeight: Theme.typography.weights.bold,
    color: AppColors.textMuted,
    marginTop: Theme.spacing.sm,
  },
});

// ================= 6. SOS SCREEN STYLES =================
export const sosStyles = StyleSheet.create({
  panicCard: {
    backgroundColor: '#FEF2F2',
    borderColor: '#FCA5A5',
    alignItems: 'center',
    padding: Theme.spacing.xxl,
    borderRadius: Theme.radii.lg,
    borderWidth: 1,
  },
  panicCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: AppColors.danger,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Theme.spacing.lg,
    ...Theme.shadows.danger,
  },
  panicTitle: {
    fontSize: Theme.typography.sizes.xl,
    fontWeight: Theme.typography.weights.black,
    color: '#DC2626',
    textAlign: 'center',
    marginBottom: 6,
  },
  panicDesc: {
    fontSize: Theme.typography.sizes.base,
    color: AppColors.textMuted,
    textAlign: 'center',
    marginBottom: Theme.spacing.lg,
    lineHeight: 18,
  },
  contactItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: AppColors.cardBg,
    borderRadius: Theme.radii.lg,
    padding: 14,
    borderWidth: 1,
    borderColor: AppColors.border,
    marginBottom: 10,
    ...Theme.shadows.card,
  },
  contactIconBox: {
    width: 40,
    height: 40,
    borderRadius: Theme.radii.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Theme.spacing.md,
  },
  callBtn: {
    borderRadius: Theme.radii.md,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  callBtnText: {
    color: '#FFFFFF',
    fontWeight: Theme.typography.weights.extraBold,
    fontSize: Theme.typography.sizes.sm,
  },
});

// ================= 7. PROFILE SCREEN STYLES =================
export const profileStyles = StyleSheet.create({
  avatarContainer: {
    alignItems: 'center',
    marginTop: -32,
    marginBottom: Theme.spacing.xl,
  },
  avatarBox: {
    width: 80,
    height: 80,
    borderRadius: Theme.radii.xl,
    backgroundColor: AppColors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: AppColors.background,
    ...Theme.shadows.elevated,
  },
  avatarInitials: {
    color: '#FFFFFF',
    fontWeight: Theme.typography.weights.black,
    fontSize: Theme.typography.sizes.display,
  },
  cameraBtn: {
    position: 'absolute',
    bottom: -4,
    right: -4,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: AppColors.primary,
    borderWidth: 2,
    borderColor: AppColors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nameText: {
    fontSize: Theme.typography.sizes.xxl,
    fontWeight: Theme.typography.weights.black,
    color: AppColors.textForeground,
    marginTop: Theme.spacing.md,
  },
  subText: {
    fontSize: Theme.typography.sizes.sm,
    fontWeight: Theme.typography.weights.medium,
    color: AppColors.textMuted,
    marginTop: 2,
  },
  infoRow: {
    paddingHorizontal: Theme.spacing.lg,
    paddingVertical: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: AppColors.border,
  },
  infoRowLast: {
    borderBottomWidth: 0,
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Theme.spacing.lg,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: AppColors.border,
  },
  logoutRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: Theme.radii.lg,
    borderWidth: 1,
    borderColor: '#FECACA',
    backgroundColor: '#FEF2F2',
    gap: 8,
  },
  logoutText: {
    fontSize: Theme.typography.sizes.md,
    fontWeight: Theme.typography.weights.black,
    color: '#DC2626',
  },
});
